"""empty message

Revision ID: d4f3263c013f
Revises: 994a688c5b82
Create Date: 2022-01-18 13:56:53.464757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4f3263c013f'
down_revision = '994a688c5b82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_ship')
    op.drop_table('shipment')
    op.drop_table('item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id_num', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=140), nullable=True),
    sa.Column('inventory', sa.INTEGER(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id_num')
    )
    op.create_table('shipment',
    sa.Column('id_num', sa.INTEGER(), nullable=False),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id_num')
    )
    op.create_table('item_ship',
    sa.Column('item_id', sa.INTEGER(), nullable=True),
    sa.Column('ship_id', sa.INTEGER(), nullable=True),
    sa.Column('inventory', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id_num'], ),
    sa.ForeignKeyConstraint(['ship_id'], ['shipment.id_num'], )
    )
    # ### end Alembic commands ###
